# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1ec0b14cc9a299e97c6090f34f22448791d4d06d11693e17fe7c189ae6049cc19cd40babb16ec1397c62496790a8daa572a6b09befabd2f375a7a41bd3a32d3

test:
  secret_key_base: 7609d59e823d3fdfdc5f38b4b7bffabcc01aac36b728ff845347611ff3bd17a9e48fcf2e0aab0b0b7882c2ee8e327c68d55cf240848c0a7ae97610fd04aed507

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
